### ISSUE TITLE
TODO: 

### ISSUE THREAD

**Issue by kirnap** [ekinakyurek/KnetLayers.jl#2]
- [ ] modify core.jl in new branch and checkout to the master
 - [ ] modify RNN.jl
 - [ ] Problematic naming convention in convolution, pooling, unpooling (GenericConv (conv or deconv), GenericPool)
 - [ ] Gan Example
 - [ ] Machine Translation Example

**Comment by ekinakyurek** [comment]
I am thinking to release v.0.1.0 what do you think? Could you review the code?

**Comment by kirnap** [comment]
Yeah, I can review but I got sick and need a week to review your code
